name: End-to-end tests
on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        run: npm install 

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          record: false
          publish-summary: true
          component: false
